/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AchievementPanel: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/system/AchievementPanel.vue')['default']
    ActionPanel: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/action/ActionPanel.vue')['default']
    AddEntryForm: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/pokedex/AddEntryForm.vue')['default']
    BarterPanel: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/system/BarterPanel.vue')['default']
    CharacterCard: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/team/CharacterCard.vue')['default']
    DebugModal: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/debug/DebugModal.vue')['default']
    DesktopSidePanel: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/sidepanel/DesktopSidePanel.vue')['default']
    DetailsModal: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/modals/DetailsModal.vue')['default']
    EventInjector: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/debug/EventInjector.vue')['default']
    HistoryModal: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/modals/HistoryModal.vue')['default']
    HistoryTurn: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/modals/HistoryTurn.vue')['default']
    LogEntry: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/debug/LogEntry.vue')['default']
    LogViewer: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/debug/LogViewer.vue')['default']
    MainMenu: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/MainMenu.vue')['default']
    MenuModal: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/modals/MenuModal.vue')['default']
    PokedexList: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/pokedex/PokedexList.vue')['default']
    PokedexManagerModal: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/modals/PokedexManagerModal.vue')['default']
    PokedexTab: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/pokedex/PokedexTab.vue')['default']
    PokedexViewList: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/pokedex/PokedexViewList.vue')['default']
    PromptViewer: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/debug/PromptViewer.vue')['default']
    QuestItem: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/system/QuestItem.vue')['default']
    QuestTab: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/system/QuestTab.vue')['default']
    RelationsTab: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/team/RelationsTab.vue')['default']
    RemoteSyncModal: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/modals/RemoteSyncModal.vue')['default']
    SettingsModal: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/modals/SettingsModal.vue')['default']
    SetupScreen: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/setup/SetupScreen.vue')['default']
    ShelterComponent: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/world/ShelterComponent.vue')['default']
    ShelterInfo: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/world/ShelterInfo.vue')['default']
    SidePanel: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/sidepanel/SidePanel.vue')['default']
    SignInPanel: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/system/SignInPanel.vue')['default']
    SkillPanel: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/system/SkillPanel.vue')['default']
    StateBrowser: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/debug/StateBrowser.vue')['default']
    StoryPanel: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/story/StoryPanel.vue')['default']
    SystemTab: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/system/SystemTab.vue')['default']
    TeamTab: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/team/TeamTab.vue')['default']
    TopBar: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/TopBar.vue')['default']
    VariableEntry: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/debug/VariableEntry.vue')['default']
    VersionModal: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/modals/VersionModal.vue')['default']
    WorldTab: typeof import('./什么我要在玄幻修仙世界种田-0楼版本/components/world/WorldTab.vue')['default']
  }
}
